### ISSUE TITLE
Issue reading smartcard

### ISSUE THREAD

**Issue by HikariWS** [mlaily/KeePass-CertificateShortcutProvider#3]
Hello, tnx for developing this plugin!

I'm trying to use it to encrypt KeePass db using a self-signed digital id stored on a smartcard.

I'm using Omnikey 3021 to read the sc and SafeSign Token Administration Utility to manage it. I used openssl following to https://www.scottbrady91.com/openssl/creating-rsa-keys-using-openssl to create the digital id (pfx) and successifully imported it to the sc.

But when I go on KeePass > Initialize Certificate Shortcut Provider > Browse certificate store, the sc is read (it blinks 3 times) but PIN isn't requested and the Windows Security dialog opens saying no certificate is available.

For testing, I also followed https://www.sonicwall.com/support/knowledge-base/how-can-i-import-certificates-into-the-ms-windows-local-machine-certificate-store/170504615105398/ to import the certificate do Windows local store. I imported it to Current User and then it was found.

Might I be doing anything wrong? Maybe Omnikey isn't supported?

**Comment by mlaily** [comment]
Hello,

> But when I go on KeePass > Initialize Certificate Shortcut Provider > Browse certificate store, the sc is read (it blinks 3 times) but PIN isn't requested and the Windows Security dialog opens saying no certificate is available.

The plugin currently displays and allows selecting a certificate from [the current user's personal certificates store], which(https://github.com/mlaily/KeePass-CertificateShortcutProvider/blob/master/CertificateShortcutProvider/KeyCreationForm.cs#L73), which I believe is the correct location to use.

If you don't see your certificate in the list, I think there might be two possible reasons:
- The hardware and driver you are using registers your certificate in another store.
- The hardware and driver you are using does not register your certificate in any Windows certificate store.

There might be more information about this in the documentation of the administration utility. I'm not sure I can provide more help, sorry.

**Comment by HikariWS** [comment]
So there's a way for the smartcard reader driver to register its certificates on windows certificate store?

Do you know some tutorial teaching how to create a self-signed certificate and import it to a sc, that's known to work? I'd like to assure I did it right so I can isolate the issue on the reader.

**Comment by mlaily** [comment]
My experience is limited, but it really depends on the hardware you use and its administration tool.

If they play nice with Windows the certificate should show up in the right certificate store, but it's not automatic.
You should refer to their documentation.

I myself spent several hours of struggle [trying to initialize a Feitian USB hardware token](https://zerowidthjoiner.net/2019/01/12/feitian-epass-nfc-security-hardware-token-smart-card-preparation) so [I could use it with my SSH client](https://zerowidthjoiner.net/2019/01/12/using-ssh-public-key-authentication-with-a-smart-card), but it will probably not help you if you don't have the same token.
